export const key_dates_list = [
    {value: "ASR Birthdate", label: "ASR Birthdate"},
    {value: "ASR Submission Date", label: "ASR Submission Date"},
    {value: "Development International Birth Date", label: "Development International Birth Date"},
    {value: "International Birth Date", label: "International Birth Date"},
    {value: "NR : Date of Inventory (STG Inventory FORM)", label: "NR : Date of Inventory (STG Inventory FORM)"},
    {value: "NR : Start Marketing Date", label: "NR : Start Marketing Date"},
    {value: "PSUR Birthdate", label: "PSUR Birthdate"},
    {value: "PSUR Submission Date", label: "PSUR Submission Date"},
    {value: "Study End Date", label: "Study End Date"},
    {value: "Study End Date Submitted", label: "Study End Date Submitted"},
    {value: "Study Results Submitted", label: "Study Results Submitted"},
    {value: "Study Start Date", label: "Study Start Date"},
];

export const operations = [
    {value: "Control site", label: "Control site"},
    {value: "Release site", label: "Release site"},
    {value: "Distributor", label: "Distributor"},
    {value: "Bulk Manufacturer", label: "Bulk Manufacturer"},
    {value: "Exploitant", label: "Exploitant"},
    {value: "Diluent Manufacturer", label: "Diluent Manufacturer"},
    {value: "Active substance Manufacturer", label: "Active substance Manufacturer"},
    {value: "Finished product Manufacturer", label: "Finished product Manufacturer"},
    {value: "Primary Packaging", label: "Primary Packaging"},
    {value: "Secondary Packaging", label: "Secondary Packaging"},
    {value: "Labelling", label: "Labelling"},
    {value: "API Suppliers", label: "API Suppliers"},
    {value: "API Manufacturer", label: "API Manufacturer"},
    {value: "Batch Release", label: "Batch Release"},
    {value: "Packaging of finished product", label: "Packaging of finished product"},
    {value: "Manufacturer", label: "Manufacturer"},
    {value: "Re-Labelling", label: "Re-Labelling"},
    {value: "Re-Packaging", label: "Re-Packaging"},
    {value: "Analytical Testing", label: "Analytical Testing"},
    {value: "Batch control/Testing", label: "Batch control/Testing"},
    {value: "Total Manufacturing", label: "Total Manufacturing"},
    {value: "Packaging", label: "Packaging"},
    {value: "Distilling", label: "Distilling"},
    {value: "Intermediate Product Manufacturing", label: "Intermediate Product Manufacturing"},
    {value: "Raw Material Supply", label: "Raw Material Supply"},
    {value: "Stability Testing", label: "Stability Testing"},
    {value: "Manufacturing Facility", label: "Manufacturing Facility"},
    {value: "Design Facility", label: "Design Facility"},
];

export const packageCondistion = [
    {value: "Atmospheric pressure limitation", label:"Atmospheric pressure limitation"},
    {value: "Avoid direct sunlight", label:"Avoid direct sunlight"},
    {value: "Between 1 and 75% relative humidity", label:"Between 1 and 75% relative humidity"},
    {value: "Between 8 and 80% RH", label:"Between 8 and 80% RH"},
    {value: "Dangerous voltage - this way up - period after opening", label:"Dangerous voltage - this way up - period after opening"},
    {value: "Do not expose to extreme heat", label:"Do not expose to extreme heat"},
    {value: "Do not freeze", label:"Do not freeze"},
    {value: "Do not refrigerate", label:"Do not refrigerate"},
    {value: "Do not refrigerate or freeze", label:"Do not refrigerate or freeze"},
    {value: "Do not store above 25°", label:"Do not store above 25°"},
    {value: "Do not store above 30°", label:"Do not store above 30°"},
    {value: "Do not store at extreme temperature and humidity", label:"Do not store at extreme temperature and humidity"},
    {value: "Fragile, handle with care", label:"Fragile, handle with care"},
    {value: "Humidity limitation", label:"Humidity limitation"},
    {value: "In order to protect from light", label:"In order to protect from light"},
    {value: "In order to protect from moisture", label:"In order to protect from moisture"},
    {value: "Keep away from sunlight", label:"Keep away from sunlight"},
    {value: "Keep dry", label:"Keep dry"},
    {value: "Keep the container in the outer carton", label:"Keep the container in the outer carton"},
    {value: "Keep the container tightly closed", label:"Keep the container tightly closed"},
    {value: "Keep the transdermal patch in the sachet until use", label:"Keep the transdermal patch in the sachet until use"},
    {value: "Lower limit of temperature", label:"Lower limit of temperature"},
];

export const product_name = [
    {value: "STG 320", label: "STG 320"},
    {value: "ALBEY", label: "ALBEY"},
    {value: "ALUSTAL", label: "ALUSTAL"},
    {value: "ALYOSTAL IDR", label: "ALYOSTAL IDR"},
    {value: "ALYOSTAL PRICK", label: "ALYOSTAL PRICK"},
    {value: "ALYOSTAL TPC", label: "ALYOSTAL TPC"},
    {value: "ALYOSTAL TPN", label: "ALYOSTAL TPN"},
    {value: "ALYOSTAL VENOM", label: "ALYOSTAL VENOM"},
    {value: "DILUENT", label: "DILUENT"},
    {value: "ORALAIR", label: "ORALAIR"},
    {value: "PHOSTAL", label: "PHOSTAL"},
    {value: "REFERENCES", label: "REFERENCES"},
    {value: "STALORAL", label: "STALORAL"},
    {value: "STALORAL 300", label: "STALORAL 300"},
];

export const procedure_type = [
    {value: "National", label: "National"},
    {value: "Centralized", label: "Centralized"},
    {value: "Decentralized", label: "Decentralized"},
    {value: "Mutual Recognition", label: "Mutual Recognition"},
];

export const apf = [
    {value: "Powder", label: "Powder"},
    {value: "Solution", label: "Solution"},
    {value: "Eye drops", label: "Eye drops"},
    {value: "Nebuliser solution", label: "Nebuliser solution"},
    {value: "Oral solution", label: "Oral solution"},
    {value: "Powder and solvent for solution for injection", label: "Powder and solvent for solution for injection"},
    {value: "Solution for injection", label: "Solution for injection"},
    {value: "Sublingual tablet", label: "Sublingual tablet"},
    {value: "Suspension for injection", label: "Suspension for injection"},
    {value: "Sieved powder", label: "Sieved powder"},
    {value: "Solution for skin-prick test", label: "Solution for skin-prick test"},
    {value: "Eye drops powder and solvent for injection", label: "Eye drops powder and solvent for injection"},
    {value: "Powder and solvent for nebuliser solution", label: "Powder and solvent for nebuliser solution"},
];

export const atc = [
    {value: "V01 - Allergens", label: "V01 - Allergens"},
    {value: "V01A - Allergens", label: "V01A - Allergens"},
    {value: "V01AA - Allergen extracts", label: "V01AA - Allergen extracts"},
    {value: "V01AA01 - Feather", label: "V01AA01 - Feather"},
    {value: "V01AA02 - Grass pollen", label: "V01AA02 - Grass pollen"},
    {value: "V01AA03 - House dust mites", label: "V01AA03 - House dust mites"},
    {value: "V01AA04 - Mould fungs and yeast fungus", label: "V01AA04 - Mould fungs and yeast fungus"},
    {value: "V01AA05 - Tree pollen", label: "V01AA05 - Tree pollen"},
    {value: "V01AA07 - Insects", label: "V01AA07 - Insects"},
    {value: "V01AA08 - Food", label: "V01AA08 - Food"},
    {value: "V01AA09 - Textiles", label: "V01AA09 - Textiles"},
    {value: "V01AA10 - Flowers", label: "V01AA10 - Flowers"},
    {value: "V01AA11 - Animals", label: "V01AA11 - Animals"},
    {value: "V01AA20 - Various", label: "V01AA20 - Various"},
    {value: "V04C - Other diagnostic agents", label: "V04C - Other diagnostic agents"},
    {value: "V04CL - Tests for allergic diseases", label: "V04CL - Tests for allergic diseases"},
    {value: "V07AB - Solvents and diluting agents", label: "V07AB - Solvents and diluting agents"},
];

export const SlType = [
    {value:'shelf life of the medicinal product as packaged for sale', label:'shelf life of the medicinal product as packaged for sale'},
    {value:'shelf life after first opening the immediate packaging', label:'shelf life after first opening the immediate packaging'},
    {value:'shelf life after dilution or reconstitution according to direction', label:'shelf life after dilution or reconstitution according to direction'},
    {value:'shelf life after incorporation into meal or pelleted feed', label:'shelf life after incorporation into meal or pelleted feed'},
    {value:'shelf life from manufacturing time', label:'shelf life from manufacturing time'},
    {value:'shelf life from the activity reference time stated on the label', label:'shelf life from the activity reference time stated on the label'},
    {value:'shelf life in unit-dose dispensing', label:'shelf life in unit-dose dispensing'}
];

export const indications = [
    {value:'10001709 - Allergic Conjunctivitis', label:'10001709 - Allergic Conjunctivitis'},
    {value:'10056352 - Allergy Test Positive', label:'10056352 - Allergy Test Positive'},
    {value:'10001728 - Allergic Rhinoconjunctivitis', label:'10001728 - Allergic Rhinoconjunctivitis'},
    {value:'10001705 - Allergic Asthma', label:'10001705 - Allergic Asthma'},
    {value:'10001721 - Allergic Reaction To Bee Sting', label:'10001721 - Allergic Reaction To Bee Sting'},
    {value:'10053462 - Allergy Test', label:'10053462 - Allergy Test'},
    {value:'10056362 - Allergy Test Negative', label:'10056362 - Allergy Test Negative'},
    {value:'10003555 - Asthma Bronchial', label:'10003555 - Asthma Bronchial'},
    {value:'10019170 - Hay Fever', label:'10019170 - Hay Fever'},
    {value:'10001726 - Allergic rhinitis due to pollen', label:'10001726 - Allergic rhinitis due to pollen'},
    {value:'10063482 - Medication Dilution', label:'10063482 - Medication Dilution'},
    {value:'10001722 - Allergic Reaction To Wasp Sting', label:'10001722 - Allergic Reaction To Wasp Sting'},
    {value:'10044314 - Tracheobronchitis', label:'10044314 - Tracheobronchitis'},
    {value:'10016015 - Eyes tearing', label:'10016015 - Eyes tearing'},
    {value:'10030048 - Ocular itching', label:'10030048 - Ocular itching'},
];

export const status = [
    {value:'Application / Submitted', label:'Application / Submitted'},
    {value:'Approval / Obtained', label:'Approval / Obtained'},
    {value:'Application / Rejected', label:'Application / Rejected'},
    {value:'Application / Withdrawn by MAH due to Safety/Efficacy', label:'Application / Withdrawn by MAH due to Safety/Efficacy'},
    {value:'Application / Withdrawn by MAH not due Safety/Efficacy', label:'Application / Withdrawn by MAH not due Safety/Efficacy'},
    {value:'Marketing Application / Dispatched To Local RA', label:'Marketing Application / Dispatched To Local RA'},
    {value:'Application / Validated (administrative / technical admissibility)', label:'Application / Validated (administrative / technical admissibility)'},
    {value:'Assessment report / received', label:'Assessment report / received'},
    {value:'Dossier Update / Submitted', label:'Dossier Update / Submitted'},
    {value:'eCTD Dossier Update / Submitted', label:'eCTD Dossier Update / Submitted'},
    {value:'Marketing / Launched', label:'Marketing / Launched'},
    {value:'Marketing / Discontinued', label:'Marketing / Discontinued'},
    {value:'Application / Dispatch Planned', label:'Application / Dispatch Planned'},
    {value:'Application / Submission Planned', label:'Application / Submission Planned'},
    {value:'Application / Approval Expected', label:'Application / Approval Expected'},
    {value:'Dossier Update / Submission Planned', label:'Dossier Update / Submission Planned'},
    {value:'eCTD Dossier Update / Submission Planned', label:'eCTD Dossier Update / Submission Planned'},
    {value:'Application / Submission of dossier update to RMS planned', label:'Application / Submission of dossier update to RMS planned'},
    {value:'Application / Dossier update submitted to CMS', label:'Application / Dossier update submitted to CMS'},
    {value:'Application / Submission to CMS Planned', label:'Application / Submission to CMS Planned'},
    {value:'MRP Application / Dossier update submitted to CMS', label:'MRP Application / Dossier update submitted to CMS'},
    {value:'National Translations / Submitted', label:'National Translations / Submitted'},
    {value:'Application / List of dispatch dates submitted', label:'Application / List of dispatch dates submitted'},
    {value:'Application / Start of procedure expected', label:'Application / Start of procedure expected'},
    {value:'MRP Application / Procedure started', label:'MRP Application / Procedure started'},
    {value:'Applicaton / CMS comments expected', label:'Applicaton / CMS comments expected'},
    {value:'Application / / CMS comments received', label:'Application / / CMS comments received'},
    {value:'Assessment Report / Expected', label:'Assessment Report / Expected'},
    {value:'MRP Assessment Report / Received', label:'MRP Assessment Report / Received'},
    {value:'Positive Opinion / Obtained', label:'Positive Opinion / Obtained'},
    {value:'MRP Application / End of procedure', label:'MRP Application / End of procedure'},
];

// export default List;
