export const key_dates_list = [
    { value: "ASR Birthdate", label: "ASR Birthdate" },
    { value: "ASR Submission Date", label: "ASR Submission Date" },
    { value: "Development International Birth Date", label: "Development International Birth Date" },
    { value: "International Birth Date", label: "International Birth Date" },
    { value: "NR : Date of Inventory (STG Inventory FORM)", label: "NR : Date of Inventory (STG Inventory FORM)" },
    { value: "NR : Start Marketing Date", label: "NR : Start Marketing Date" },
    { value: "PSUR Birthdate", label: "PSUR Birthdate" },
    { value: "PSUR Submission Date", label: "PSUR Submission Date" },
    { value: "Study End Date", label: "Study End Date" },
    { value: "Study End Date Submitted", label: "Study End Date Submitted" },
    { value: "Study Results Submitted", label: "Study Results Submitted" },
    { value: "Study Start Date", label: "Study Start Date" },
];

export const operations = [
    { value: "Control site", label: "Control site" },
    { value: "Release site", label: "Release site" },
    { value: "Distributor", label: "Distributor" },
    { value: "Bulk Manufacturer", label: "Bulk Manufacturer" },
    { value: "Exploitant", label: "Exploitant" },
    { value: "Diluent Manufacturer", label: "Diluent Manufacturer" },
    { value: "Active substance Manufacturer", label: "Active substance Manufacturer" },
    { value: "Finished product Manufacturer", label: "Finished product Manufacturer" },
    { value: "Primary Packaging", label: "Primary Packaging" },
    { value: "Secondary Packaging", label: "Secondary Packaging" },
    { value: "Labelling", label: "Labelling" },
    { value: "API Suppliers", label: "API Suppliers" },
    { value: "API Manufacturer", label: "API Manufacturer" },
    { value: "Batch Release", label: "Batch Release" },
    { value: "Packaging of finished product", label: "Packaging of finished product" },
    { value: "Manufacturer", label: "Manufacturer" },
    { value: "Re-Labelling", label: "Re-Labelling" },
    { value: "Re-Packaging", label: "Re-Packaging" },
    { value: "Analytical Testing", label: "Analytical Testing" },
    { value: "Batch control/Testing", label: "Batch control/Testing" },
    { value: "Total Manufacturing", label: "Total Manufacturing" },
    { value: "Packaging", label: "Packaging" },
    { value: "Distilling", label: "Distilling" },
    { value: "Intermediate Product Manufacturing", label: "Intermediate Product Manufacturing" },
    { value: "Raw Material Supply", label: "Raw Material Supply" },
    { value: "Stability Testing", label: "Stability Testing" },
    { value: "Manufacturing Facility", label: "Manufacturing Facility" },
    { value: "Design Facility", label: "Design Facility" },
];

export const packageCondistion = [
    { value: 'Protect from Light', label: 'Protect from Light' },
    { value: 'Atmospheric pressure limitation *', label: 'Atmospheric pressure limitation *' },
    { value: 'Between 8 and 80 % RH', label: 'Between 8 and 80 % RH' },
    { value: 'Keep the container tightly closed', label: 'Keep the container tightly closed' },
    { value: 'Do not store above 25°C', label: 'Do not store above 25°C' },
    { value: 'Do not store above 30°C', label: 'Do not store above 30°C' },
    { value: 'Store below 25°C', label: 'Store below 25°C' },
    { value: 'Store below 30°C', label: 'Store below 30°C' },
    { value: 'Store in a refrigerator (2°C - 8°C)', label: 'Store in a refrigerator (2°C - 8°C)' },
    { value: 'Store and transport refrigerated (2°C - 8°C)', label: 'Store and transport refrigerated (2°C - 8°C)' },
    { value: 'Store in a freezer', label: 'Store in a freezer' },
    { value: 'Store and transport frozen', label: 'Store and transport frozen' },
    { value: 'Do not refrigerate or freeze', label: 'Do not refrigerate or freeze' },
    { value: 'Do not refrigerate', label: 'Do not refrigerate' },
    { value: 'Do not freeze', label: 'Do not freeze' },
    { value: 'Store in the original package', label: 'Store in the original package' },
    { value: 'Keep the container in the outer carton', label: 'Keep the container in the outer carton' },
    { value: 'Protect from frost', label: 'Protect from frost' },
    { value: 'In order to protect from moisture', label: 'In order to protect from moisture' },
    { value: 'In order to protect from light', label: 'In order to protect from light' },
    { value: 'This medicinal product does not require any special temperature storage conditions', label: 'This medicinal product does not require any special temperature storage conditions' },
    { value: 'This medicinal product does not require any special storage conditions', label: 'This medicinal product does not require any special storage conditions' },
    { value: 'Do not expose to extreme heat', label: 'Do not expose to extreme heat' },
    { value: 'Store at temperatures below -140°C in the vapour phase of liquid nitrogen', label: 'Store at temperatures below -140°C in the vapour phase of liquid nitrogen' },
    { value: 'Keep the transdermal patch in the sachet until use', label: 'Keep the transdermal patch in the sachet until use' },
    { value: 'This veterinary medicinal product does not require any special temperature storage conditions', label: 'This veterinary medicinal product does not require any special temperature storage conditions' },
    { value: 'This veterinary medicinal product does not require any special storage conditions', label: 'This veterinary medicinal product does not require any special storage conditions' },
    { value: 'Protect from direct sunlight', label: 'Protect from direct sunlight' },
    { value: 'Store in a dry place', label: 'Store in a dry place' },
    { value: 'Protect from light', label: 'Protect from light' },
    { value: 'Store in the original container', label: 'Store in the original container' },
    { value: 'Protect From Moisture', label: 'Protect From Moisture' },
    { value: 'Between 30 and 75 % Relative Humidity', label: 'Between 30 and 75 % Relative Humidity' },
    { value: 'Temperature between -20°C and -10°C', label: 'Temperature between -20°C and -10°C' },
    { value: 'Temperature should not exceed 40°C', label: 'Temperature should not exceed 40°C' },
    { value: 'Temperature between 30°C and 40°C', label: 'Temperature between 30°C and 40°C' },
    { value: 'Temperature between 15°C and 30°C', label: 'Temperature between 15°C and 30°C' },
    { value: 'Temperature between 8°C and 15°C', label: 'Temperature between 8°C and 15°C' },
    { value: 'Temperature between 2°C and 8°C', label: 'Temperature between 2°C and 8°C' },
    { value: 'Do not store at extreme temperature and humidity', label: 'Do not store at extreme temperature and humidity' },
    { value: 'Avoid direct sunlight', label: 'Avoid direct sunlight' },
    { value: 'OTHER *', label: 'OTHER *' },
    { value: 'P411 + P235 - Store at temperatures not exceeding … oC/…oF. Keep cool. *', label: 'P411 + P235 - Store at temperatures not exceeding … oC/…oF. Keep cool. *' },
    { value: 'P410 + P412 - Protect from sunlight. Do no expose to temperatures exceeding 50 oC/122oF. *', label: 'P410 + P412 - Protect from sunlight. Do no expose to temperatures exceeding 50 oC/122oF. *' },
    { value: 'P410 + P403 - Protect from sunlight. Store in a well-ventilated place.', label: 'P410 + P403 - Protect from sunlight. Store in a well-ventilated place.' },
    { value: 'P403 + P235 - Store in a well-ventilated place. Keep cool.', label: 'P403 + P235 - Store in a well-ventilated place. Keep cool.' },
    { value: 'P403 + P233 - Store in a well-ventilated place. Keep container tightly closed.', label: 'P403 + P233 - Store in a well-ventilated place. Keep container tightly closed.' },
    { value: 'P402 + P404 - Store in a dry place. Store in a closed container.', label: 'P402 + P404 - Store in a dry place. Store in a closed container.' },
    { value: 'P422 - Store contents under … *', label: 'P422 - Store contents under … *' },
    { value: 'P420 - Store away from other materials.', label: 'P420 - Store away from other materials.' },
    { value: 'P413 - Store bulk masses greater than … kg/… lbs at temperatures not exceeding … oC/…oF. *', label: 'P413 - Store bulk masses greater than … kg/… lbs at temperatures not exceeding … oC/…oF. *' },
    { value: 'P412 - Do not expose to temperatures exceeding 50 oC/122oF. *', label: 'P412 - Do not expose to temperatures exceeding 50 oC/122oF. *' },
    { value: 'P411 - Store at temperatures not exceeding … oC/…oF. *', label: 'P411 - Store at temperatures not exceeding … oC/…oF. *' },
    { value: 'P410 - Protect from sunlight.', label: 'P410 - Protect from sunlight.' },
    { value: 'P407 - Maintain air gap between stacks/pallets.', label: 'P407 - Maintain air gap between stacks/pallets.' },
    { value: 'P406 - Store in corrosive resistant/… container with a resistant inner liner.', label: 'P406 - Store in corrosive resistant/… container with a resistant inner liner.' },
    { value: 'P405 - Store locked up.', label: 'P405 - Store locked up.' },
    { value: 'P404 - Store in a closed container.', label: 'P404 - Store in a closed container.' },
    { value: 'P403 - Store in a well-ventilated place.', label: 'P403 - Store in a well-ventilated place.' },
    { value: 'P402 - Store in a dry place.', label: 'P402 - Store in a dry place.' },
    { value: 'P401 - Store … *', label: 'P401 - Store … *' },
    { value: 'Dangerous voltage - This way up - Period-after-opening (Commission Directive 2003/80/EC)', label: 'Dangerous voltage - This way up - Period-after-opening (Commission Directive 2003/80/EC)' },
    { value: 'WEEE Marking of electrical and electronic equipment in accordance with Article 11(2) of Directive 2002/96/EC (WEEE) (EN 50419:2006)', label: 'WEEE Marking of electrical and electronic equipment in accordance with Article 11(2) of Directive 2002/96/EC (WEEE) (EN 50419:2006)' },
    { value: 'Humidity limitation *', label: 'Humidity limitation *' },
    { value: 'Temperature limit  *', label: 'Temperature limit  *' },
    { value: 'Upper limit of temperature *', label: 'Upper limit of temperature *' },
    { value: 'Lower limit of temperature *', label: 'Lower limit of temperature *' },
    { value: 'Keep dry', label: 'Keep dry' },
    { value: 'Protect from radioactive sources', label: 'Protect from radioactive sources' },
    { value: 'Protect from heat and radioactive sources', label: 'Protect from heat and radioactive sources' },
    { value: 'Keep away from sunlight', label: 'Keep away from sunlight' },
    { value: 'Fragile, handle with care', label: 'Fragile, handle with care' },
    { value: 'Do not store at extreme temperature and humidity', label: 'Do not store at extreme temperature and humidity' },
    { value: 'Between 1 and 30°', label: 'Between 1 and 30°' },
    { value: 'Temperature limitation for storage', label: 'Temperature limitation for storage' },
    { value: 'STORE AT 25°C', label: 'STORE AT 25°C' },
    { value: 'STORE AT ROOM TEMPERATURE (1°C-25°C)', label: 'STORE AT ROOM TEMPERATURE (1°C-25°C)' },
    { value: 'STORE AT 25°C OR BELOW', label: 'STORE AT 25°C OR BELOW' },
    { value: 'STORE AT ROOM TEMPERATURE (15°C-30°C)', label: 'STORE AT ROOM TEMPERATURE (15°C-30°C)' },

];

export const product_name = [
    { value: "STG 320", label: "STG 320" },
    { value: "ALBEY", label: "ALBEY" },
    { value: "ALUSTAL", label: "ALUSTAL" },
    { value: "ALYOSTAL IDR", label: "ALYOSTAL IDR" },
    { value: "ALYOSTAL PRICK", label: "ALYOSTAL PRICK" },
    { value: "ALYOSTAL TPC", label: "ALYOSTAL TPC" },
    { value: "ALYOSTAL TPN", label: "ALYOSTAL TPN" },
    { value: "ALYOSTAL VENOM", label: "ALYOSTAL VENOM" },
    { value: "DILUENT", label: "DILUENT" },
    { value: "ORALAIR", label: "ORALAIR" },
    { value: "PHOSTAL", label: "PHOSTAL" },
    { value: "REFERENCES", label: "REFERENCES" },
    { value: "STALORAL", label: "STALORAL" },
    { value: "STALORAL 300", label: "STALORAL 300" },
];

export const procedure_type = [
    { value: "National", label: "National" },
    { value: "Centralized", label: "Centralized" },
    { value: "Decentralized", label: "Decentralized" },
    { value: "Mutual Recognition", label: "Mutual Recognition" },
];

export const apf = [
    { value: "Concentrate for dispersion for infusion", label: "Concentrate for dispersion for infusion" },
    { value: "Eye drops", label: "Eye drops" },
    { value: "Eye drops powder and solvent for injection", label: "Eye drops powder and solvent for injection" },
    { value: "Film-coated tablets", label: "Film-coated tablets" },
    { value: "Nebuliser solution", label: "Nebuliser solution" },
    { value: "Oral solution", label: "Oral solution" },
    { value: "Powder", label: "Powder" },
    { value: "Powder and solvent for nebuliser solution", label: "Powder and solvent for nebuliser solution" },
    { value: "Powder and solvent for solution for injection", label: "Powder and solvent for solution for injection" },
    { value: "Powder for concentrate for solution for infusion", label: "Powder for concentrate for solution for infusion" },
    { value: "Powder for solution for injection/infusion", label: "Powder for solution for injection/infusion" },
    { value: "Sieved powder", label: "Sieved powder" },
    { value: "Solution", label: "Solution" },
    { value: "Solution for injection", label: "Solution for injection" },
    { value: "Solution for skin-prick test", label: "Solution for skin-prick test" },
    { value: "Sublingual tablet", label: "Sublingual tablet" },
    { value: "Suspension for injection", label: "Suspension for injection" },
];

export const adpf = [
    { value: 'Same as authorised pharmaceutical form', label: 'Same as authorised pharmaceutical form' },
    { value: 'Concentrate for dispersion for infusion', label: 'Concentrate for dispersion for infusion' },
    { value: 'Eye drops', label: 'Eye drops' },
    { value: 'Eye drops powder and solvent for injection', label: 'Eye drops powder and solvent for injection' },
    { value: 'Film-coated tablets', label: 'Film-coated tablets' },
    { value: 'Nebuliser solution', label: 'Nebuliser solution' },
    { value: 'Oral solution', label: 'Oral solution' },
    { value: 'Powder', label: 'Powder' },
    { value: 'Powder and solvent for nebuliser solution', label: 'Powder and solvent for nebuliser solution' },
    { value: 'Powder and solvent for solution for injection', label: 'Powder and solvent for solution for injection' },
    { value: 'Powder for concentrate for solution for infusion', label: 'Powder for concentrate for solution for infusion' },
    { value: 'Powder for solution for injection/infusion', label: 'Powder for solution for injection/infusion' },
    { value: 'Sieved powder', label: 'Sieved powder' },
    { value: 'Solution', label: 'Solution' },
    { value: 'Solution for injection', label: 'Solution for injection' },
    { value: 'Solution for skin-prick test', label: 'Solution for skin-prick test' },
    { value: 'Sublingual tablet', label: 'Sublingual tablet' },
    { value: 'Suspension for injection', label: 'Suspension for injection' },
];

export const atc = [
    { value: "N06AX22 - Psychoanaleptics, other antidepressants", label: "N06AX22 - Psychoanaleptics, other antidepressants" },
    { value: "L01DB11 - Antineoplastic agents, anthracyclines, and related substances", label: "L01DB11 - Antineoplastic agents, anthracyclines, and related substances" },
    { value: "L01CE02 - Topoisomerase 1 (TOP1) inhibitors", label: "L01CE02 - Topoisomerase 1 (TOP1) inhibitors" },
    { value: "L01XX24 - Antineoplastic and immunomodulating agents, other antineoplastic agents", label: "L01XX24 - Antineoplastic and immunomodulating agents, other antineoplastic agents" },
    { value: "L01BC59 - Antineoplastic agents, antimetabolites", label: "L01BC59 - Antineoplastic agents, antimetabolites" },
    { value: "A07BA01 - Medicinal charcoal", label: "A07BA01 - Medicinal charcoal" },
    { value: "A07BA51 - Medicinal charcoal, combinations", label: "A07BA51 - Medicinal charcoal, combinations" },
    { value: "A10AB01 - insulin (human)", label: "A10AB01 - insulin (human)" },
    { value: "A10AB02 - Insulin (beef)", label: "A10AB02 - Insulin (beef)" },
    { value: "A10AB03 - Insulin (pork)", label: "A10AB03 - Insulin (pork)" },
    { value: "A10AB04 - Insulin lispro", label: "A10AB04 - Insulin lispro" },
    { value: "A10AB05 - Insulin aspart", label: "A10AB05 - Insulin aspart" },
    { value: "A10AB06 - Insulin glulisine", label: "A10AB06 - Insulin glulisine" },
    { value: "A10AB30 - Combinations ", label: "A10AB30 - Combinations " },
    { value: "J07BX03 - Covid-19 vaccines", label: "J07BX03 - Covid-19 vaccines" },
    { value: "L01XX51 - Talimogene laherparepvec", label: "L01XX51 - Talimogene laherparepvec" },
    { value: "L01AG01 - Etoglucid ", label: "L01AG01 - Etoglucid " },
    { label: 'L01AB01 - Busulfan', value: 'L01AB01 - Busulfan' },
    { label: 'L01AB02 - Treosulfan', value: 'L01AB02 - Treosulfan' },
    { label: 'L01AB03 - Mannosulfan', value: 'L01AB03 - Mannosulfan' },
    { label: 'L01DA01 - Dactinomycin', value: 'L01DA01 - Dactinomycin' },
    { label: 'L03AB16 - Peginterferon alfacon-2', value: 'L03AB16 - Peginterferon alfacon-2' },
    { label: 'L03AB60 - Peginterferon alfa-2b, combinations', value: 'L03AB60 - Peginterferon alfa-2b, combinations' },
    { label: 'L03AB61 - Peginterferon alfa-2a, combinations', value: 'L03AB61 - Peginterferon alfa-2a, combinations' },
];

export const SlType = [
    { value: 'shelf life of the medicinal product as packaged for sale', label: 'shelf life of the medicinal product as packaged for sale' },
    { value: 'shelf life after first opening the immediate packaging', label: 'shelf life after first opening the immediate packaging' },
    { value: 'shelf life after dilution or reconstitution according to direction', label: 'shelf life after dilution or reconstitution according to direction' },
    { value: 'shelf life after incorporation into meal or pelleted feed', label: 'shelf life after incorporation into meal or pelleted feed' },
    { value: 'shelf life from manufacturing time', label: 'shelf life from manufacturing time' },
    { value: 'shelf life from the activity reference time stated on the label', label: 'shelf life from the activity reference time stated on the label' },
    { value: 'shelf life in unit-dose dispensing', label: 'shelf life in unit-dose dispensing' }
];

export const indications = [
    { value: '10002043 - Anaemia folate deficiency', label: '10002043 - Anaemia folate deficiency' },
    { value: '10066468 - Anaemia of pregnancy', label: '10066468 - Anaemia of pregnancy' },
    { value: '10002080 - Anaemia vitamin B12 deficiency', label: '10002080 - Anaemia vitamin B12 deficiency' },
    { value: '10002081 - Anaemia vitamin B6 deficiency', label: '10002081 - Anaemia vitamin B6 deficiency' },
    { value: '10081878 - Autosomal recessive megaloblastic anaemia', label: '10081878 - Autosomal recessive megaloblastic anaemia' },
    { value: '10083911 - Congenital hypotransferrinaemia', label: '10083911 - Congenital hypotransferrinaemia' },
    { value: '10061101 - Deficiency anaemia', label: '10061101 - Deficiency anaemia' },
    { value: '10084860 - Hypotransferrinaemia', label: '10084860 - Hypotransferrinaemia' },
    { value: '10022972 - Iron deficiency anaemia', label: '10022972 - Iron deficiency anaemia' },
    { value: '10034695 - Pernicious anaemia', label: '10034695 - Pernicious anaemia' },
    { value: '10037006 - Protein deficiency anaemia', label: '10037006 - Protein deficiency anaemia' },
    { value: '10086662 - Scorbutic anaemia', label: '10086662 - Scorbutic anaemia' },
    { value: '10042272 - Subacute combined cord degeneration', label: '10042272 - Subacute combined cord degeneration' },
    { value: '10084086 - Transcobalamin deficiency', label: '10084086 - Transcobalamin deficiency' },
    { value: '10029104 - Neoplasms benign, malignant and unspecified (incl cysts and polyps)', label: '10029104 - Neoplasms benign, malignant and unspecified (incl cysts and polyps)' },
    { value: '10026346 - Malignant neoplasm of pharynx, unspecified', label: '10026346 - Malignant neoplasm of pharynx, unspecified' },
    { value: "10026649 - Malignant neoplasm of Waldeyer's ring	", label: "10026649 - Malignant neoplasm of Waldeyer's ring	" },
    { value: '10034819 - Pharyngeal cancer stage unspecified', label: '10034819 - Pharyngeal cancer stage unspecified' },
    { value: '10034857 - Pharynx neoplasm malignant', label: '10034857 - Pharynx neoplasm malignant' },
    { value: '10006288 - Breast neoplasms benign (incl nipple)', label: '10006288 - Breast neoplasms benign (incl nipple)' },
    { value: '10006291 - Breast neoplasms malignant and unspecified (incl nipple)', label: '10006291 - Breast neoplasms malignant and unspecified (incl nipple)' },
    { value: '10040899 - Cutaneous neoplasms benign', label: '10040899 - Cutaneous neoplasms benign' },
    { value: '10014710 - Endocrine neoplasms benign', label: '10014710 - Endocrine neoplasms benign' },
    { value: '10014713 - Endocrine neoplasms malignant and unspecified', label: '10014713 - Endocrine neoplasms malignant and unspecified' },
    { value: '10017987 - Gastrointestinal neoplasms benign', label: '10017987 - Gastrointestinal neoplasms benign' },
    { value: '10017991 - Gastrointestinal neoplasms malignant and unspecified', label: '10017991 - Gastrointestinal neoplasms malignant and unspecified' },
    { value: '10018865 - Haematopoietic neoplasms (excl leukaemias and lymphomas)', label: '10018865 - Haematopoietic neoplasms (excl leukaemias and lymphomas)' },
];

export const route_admin = [
    { value: 'Cutaneous use', label: 'Cutaneous use' },
    { value: 'Intrademal use', label: 'Intrademal use' },
    { value: 'Eye drops', label: 'Eye drops' },
    { value: 'Nasal use', label: 'Nasal use' },
    { value: 'Ocular use', label: 'Ocular use' },
    { value: 'Subcutaneous use', label: 'Subcutaneous use' },
    { value: 'Sublingual use', label: 'Sublingual use' },
    { value: 'Oral use', label: 'Oral use' },
    { value: 'Intravenous use', label: 'Intravenous use' },
];

export const status = [
    { value: 'Approval - Approval / Expiry', label: 'Approval - Approval / Expiry' },
    { value: 'Approval - Approval / Obtained', label: 'Approval - Approval / Obtained' },
    { value: 'Approval - Conditional Approval / Obtained', label: 'Approval - Conditional Approval / Obtained' },
    { value: 'Assessment Report Receipt / Question received', label: 'Assessment Report Receipt / Question received' },
    { value: 'Assessment Report Receipt / Received', label: 'Assessment Report Receipt / Received' },
    { value: 'Assessment Report Receipt / Received/Conditionnal approval', label: 'Assessment Report Receipt / Received/Conditionnal approval' },
    { value: 'Assessment Report Receipt / Submitted', label: 'Assessment Report Receipt / Submitted' },
    { value: 'Dossier Closing Sequence / End of procedure', label: 'Dossier Closing Sequence / End of procedure' },
    { value: 'Dossier Closing Sequence / Submitted', label: 'Dossier Closing Sequence / Submitted' },
    { value: 'Dossier Dispatch / Dispatched To Local RA', label: 'Dossier Dispatch / Dispatched To Local RA' },
    { value: 'Dossier Dispatch / List of dispatch dates submitted', label: 'Dossier Dispatch / List of dispatch dates submitted' },
    { value: 'Dossier Dispatch / Submitted', label: 'Dossier Dispatch / Submitted' },
    { value: 'Dossier Initial Submission / Application Submitted', label: 'Dossier Initial Submission / Application Submitted' },
    { value: 'Dossier Initial Submission / Expiry', label: 'Dossier Initial Submission / Expiry' },
    { value: 'Dossier Initial Submission / Received', label: 'Dossier Initial Submission / Received' },
    { value: 'Dossier Initial Submission / Rejected', label: 'Dossier Initial Submission / Rejected' },
    { value: 'Dossier Initial Submission / Submission Deadline to HA', label: 'Dossier Initial Submission / Submission Deadline to HA' },
    { value: 'Dossier Initial Submission / Submission Planned', label: 'Dossier Initial Submission / Submission Planned' },
    { value: 'Dossier Initial Submission / Submitted', label: 'Dossier Initial Submission / Submitted' },
    { value: 'Dossier Initial Submission / Validated (administrative / technical admissibility)', label: 'Dossier Initial Submission / Validated (administrative / technical admissibility)' },
    { value: 'Dossier Initial Submission / Withdrawn', label: 'Dossier Initial Submission / Withdrawn' },
    { value: 'Dossier Technical Rejection / Received', label: 'Dossier Technical Rejection / Received' },
    { value: 'Dossier Update Submission / Submission Planned', label: 'Dossier Update Submission / Submission Planned' },
    { value: 'Dossier Update Submission / Submitted', label: 'Dossier Update Submission / Submitted' },
    { value: 'Dossier Validation or Fileable Confirmation / Admissibility received', label: 'Dossier Validation or Fileable Confirmation / Admissibility received' },
    { value: 'Dossier Validation or Fileable Confirmation / Validated', label: 'Dossier Validation or Fileable Confirmation / Validated' },
    { value: 'Final Opinion Receipt / Obtained', label: 'Final Opinion Receipt / Obtained' },
    { value: 'Notification Submission / Submitted', label: 'Notification Submission / Submitted' },
    { value: 'Preliminary Response Receipt / Received', label: 'Preliminary Response Receipt / Received' },
    { value: 'Procedure Complete / End of Procedure', label: 'Procedure Complete / End of Procedure' },
    { value: 'Revoked by HA due to S/E / Obtained', label: 'Revoked by HA due to S/E / Obtained' },
    { value: 'Revoked by HA not due to S/E / Obtained', label: 'Revoked by HA not due to S/E / Obtained' },
    { value: 'Withdrawal / Obtained', label: 'Withdrawal / Obtained' },
    { value: 'Withdrawal / Submitted', label: 'Withdrawal / Submitted' },
    { value: 'Withdrawal / Withdrawn', label: 'Withdrawal / Withdrawn' },
    { value: 'Withdrawal Due to S/E / Withdrawn Due To S/E', label: 'Withdrawal Due to S/E / Withdrawn Due To S/E' },
    { value: 'Withdrawal not due to S/E / Withdrawn NOT Due To S/E', label: 'Withdrawal not due to S/E / Withdrawn NOT Due To S/E' },
];

// export default List;
